filters:
  - filter_type: file
    file_format: KEYVALUEJSON
    source_language: en
    source_file: translations/en.json
    translation_files_expression: 'translations/<lang>.json'
settings:
  pr_branch_name: automated/transifex_update_<br_unique_id>


# [o:openmrs:p:openmrs-test:r:sample-resource]
# file_filter            = translations/<lang>.json
# source_file            = translations/en.json
# source_lang            = en
# type                   = KEYVALUEJSON
# minimum_perc           = 0
# replace_edited_strings = false
# keep_translations      = false
